var DataSource = [
    {
      "id": 1,
      "agency": "51st Engineer Brigade, Philippine Army",
      "donations": 44,
      "seats": 1,
      "tableAssignment": "22",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 2,
      "agency": "Abenson Group of Companies",
      "donations": 39,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 3,
      "agency": "Alaska Milk Corporation, San Pedro Laguna",
      "donations": 52,
      "seats": 1,
      "tableAssignment": "22",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 4,
      "agency": "ASA Philippines Foundation Inc.",
      "donations": 36,
      "seats": 1,
      "tableAssignment": "23",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 5,
      "agency": "Asia Pacific College",
      "donations": 37,
      "seats": 1,
      "tableAssignment": "23",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 6,
      "agency": "Barangay Balibago",
      "donations": 33,
      "seats": 1,
      "tableAssignment": "23",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 7,
      "agency": "Berjaya Philippines",
      "donations": 34,
      "seats": 2,
      "tableAssignment": "23",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 8,
      "agency": "Binangonan Life Savers, Inc.",
      "donations": 62,
      "seats": 1,
      "tableAssignment": "23",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 9,
      "agency": "Bureau of Customs",
      "donations": 45,
      "seats": 1,
      "tableAssignment": "23",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 10,
      "agency": "Bureau of Fire Protection, National Capital Region",
      "donations": 69,
      "seats": 1,
      "tableAssignment": "23",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 11,
      "agency": "Burlington",
      "donations": 59,
      "seats": 1,
      "tableAssignment": "23",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 12,
      "agency": "California Clothings Inc.",
      "donations": 55,
      "seats": 1,
      "tableAssignment": "23",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 13,
      "agency": "Cathedral of Praise",
      "donations": 92,
      "seats": 1,
      "tableAssignment": "23",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 14,
      "agency": "Cavite Naval Hospital",
      "donations": 59,
      "seats": 1,
      "tableAssignment": "24",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 15,
      "agency": "Centro Manufacturing Corporation",
      "donations": 61,
      "seats": 1,
      "tableAssignment": "24",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 16,
      "agency": "Christine Village Homeowners Association Inc. ",
      "donations": 65,
      "seats": 1,
      "tableAssignment": "24",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 17,
      "agency": "Christ's Commission Fellowship - Baliuag, Bulacan",
      "donations": 66,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 18,
      "agency": "City of Biñan Triskelion Executive Council",
      "donations": 32,
      "seats": 1,
      "tableAssignment": "24",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 19,
      "agency": "Civic Merchandising Inc",
      "donations": 40,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 20,
      "agency": "Civil Aviation Authority of the Philippines",
      "donations": 46,
      "seats": 1,
      "tableAssignment": "24",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 21,
      "agency": "Civil Service Commission",
      "donations": 60,
      "seats": 1,
      "tableAssignment": "24",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 22,
      "agency": "Coca-Cola Beverages Philippines, Inc.",
      "donations": 43,
      "seats": 1,
      "tableAssignment": "24",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 23,
      "agency": "De La Salle Araneta University",
      "donations": 43,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 24,
      "agency": "De La Salle University – COSCA LOVE",
      "donations": 75,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 25,
      "agency": "Department Of Health Center for Health Development - CaLaBaRZon",
      "donations": 95,
      "seats": 5,
      "tableAssignment": "1 presidential 4 - table 24",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 26,
      "agency": "Department of Health Metro Manila - Center for Health Development",
      "donations": 67,
      "seats": 1,
      "tableAssignment": "25",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 27,
      "agency": "Don Bosco School (Salesian Sisters) Inc.",
      "donations": 37,
      "seats": 1,
      "tableAssignment": "25",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 28,
      "agency": "Emperador Distillers Inc.",
      "donations": 97,
      "seats": 1,
      "tableAssignment": "25",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 29,
      "agency": "Eulogio \"Amang\" Rodriguez Institute of Science and Technology",
      "donations": 61,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 30,
      "agency": "Far Eastern University - Junior  Medical Society",
      "donations": 56,
      "seats": 1,
      "tableAssignment": "25",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 31,
      "agency": "Fatima Church San Pedro",
      "donations": 30,
      "seats": 1,
      "tableAssignment": "25",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 32,
      "agency": "Firefly Electric Lighting Corporation",
      "donations": 76,
      "seats": 1,
      "tableAssignment": "25",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 33,
      "agency": "Five9 Philippines, Inc.",
      "donations": 76,
      "seats": 1,
      "tableAssignment": "25",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 34,
      "agency": "Gemphil Technologies Inc.",
      "donations": 36,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 35,
      "agency": "GK Towerville - Bulacan",
      "donations": 35,
      "seats": 1,
      "tableAssignment": "25",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 36,
      "agency": "Glades International Corporation",
      "donations": 41,
      "seats": 2,
      "tableAssignment": "25",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 37,
      "agency": "Grace General Hospital, Inc.",
      "donations": 53,
      "seats": 1,
      "tableAssignment": "25",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 38,
      "agency": "Higher Rock Christian Church",
      "donations": 39,
      "seats": 1,
      "tableAssignment": "26",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 39,
      "agency": "Hizon Laboratories, Incorporated",
      "donations": 56,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 40,
      "agency": "Honda Cars Philippines Inc. ",
      "donations": 72,
      "seats": 1,
      "tableAssignment": "26",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 41,
      "agency": "Iglesia ng Dios Kay Cristo Jesus Haligi at Suhay ng Katotohanan",
      "donations": 88,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 42,
      "agency": "Infosys BPM Limited - Philippine Branch",
      "donations": 63,
      "seats": 1,
      "tableAssignment": "26",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 43,
      "agency": "Jollibee Region IV-A",
      "donations": 62,
      "seats": 1,
      "tableAssignment": "26",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 44,
      "agency": "Josefina Manufacturing Inc. ",
      "donations": 55,
      "seats": 1,
      "tableAssignment": "26",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 45,
      "agency": "Kaertech Electronics Philippines",
      "donations": 57,
      "seats": 2,
      "tableAssignment": "26",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 46,
      "agency": "Kawit Rural Health Unit ",
      "donations": 73,
      "seats": 1,
      "tableAssignment": "26",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 47,
      "agency": "Kilusan sa Jollibee",
      "donations": 70,
      "seats": 1,
      "tableAssignment": "26",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 48,
      "agency": "Kythe A+",
      "donations": 42,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 49,
      "agency": "La Consolacion College, Deparo Novaliches",
      "donations": 53,
      "seats": 1,
      "tableAssignment": "26",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 50,
      "agency": "La Filipina Uy Gongco",
      "donations": 99,
      "seats": 1,
      "tableAssignment": "26",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 51,
      "agency": "La Salle Green Hills",
      "donations": 83,
      "seats": 1,
      "tableAssignment": "27",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 52,
      "agency": "Lafarge Holcim Aggregates Inc.",
      "donations": 40,
      "seats": 1,
      "tableAssignment": "27",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 53,
      "agency": "Lyceum of the Philippines University – Laguna",
      "donations": 58,
      "seats": 1,
      "tableAssignment": "27",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 54,
      "agency": "Magic-5 PUP",
      "donations": 80,
      "seats": 1,
      "tableAssignment": "27",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 55,
      "agency": "Magnolia Incorporated",
      "donations": 40,
      "seats": 1,
      "tableAssignment": "27",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 56,
      "agency": "Makati Shangri-La Hotel",
      "donations": 59,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 57,
      "agency": "Mallers Management Corporation",
      "donations": 95,
      "seats": 1,
      "tableAssignment": "27",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 58,
      "agency": "Manila Ocean Park and Hotel H2O ",
      "donations": 37,
      "seats": 1,
      "tableAssignment": "27",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 59,
      "agency": "Manuel L. Quezon University",
      "donations": 77,
      "seats": 1,
      "tableAssignment": "27",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 60,
      "agency": "Marikina Valley Medical Center",
      "donations": 46,
      "seats": 1,
      "tableAssignment": "27",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 61,
      "agency": "Metropolitan Manila Development Authority",
      "donations": 89,
      "seats": 2,
      "tableAssignment": "27",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 62,
      "agency": "Meycauayan Doctors Hospital and Medical Center, Meycauayan City, Bulacan",
      "donations": 69,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 63,
      "agency": "MN Electro Industrial Supply & Services, Inc.",
      "donations": 40,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 64,
      "agency": "Multigeneration of Active Apostolic Guardians Association of the Philippines (MAAGAP) Inc.",
      "donations": 52,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 65,
      "agency": "Municipal Government of Tanay, Rizal",
      "donations": 36,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 66,
      "agency": "National Bureau of Investigation",
      "donations": 33,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 67,
      "agency": "National Police Commission",
      "donations": 34,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 68,
      "agency": "National University",
      "donations": 68,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 69,
      "agency": "Naval Installation Command, Philippine Navy ",
      "donations": 89,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 70,
      "agency": "Nokia Technology Center Philippines, Inc.  ",
      "donations": 60,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 71,
      "agency": "Novotel, Manila",
      "donations": 43,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 72,
      "agency": "Office of Congressman \"Yul Servo\" Nieto",
      "donations": 31,
      "seats": 0,
      "tableAssignment": "",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 73,
      "agency": "Order of the Triskelion, Bulacan Chapter",
      "donations": 55,
      "seats": 1,
      "tableAssignment": "28",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 74,
      "agency": "P. IMES Corp.",
      "donations": 86,
      "seats": 2,
      "tableAssignment": "29",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 75,
      "agency": "Pfizer Philippines Foundation",
      "donations": 69,
      "seats": 2,
      "tableAssignment": "29",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 76,
      "agency": "PHAPCares Foundation, Inc.",
      "donations": 34,
      "seats": 1,
      "tableAssignment": "29",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 77,
      "agency": "Philippine National Police - National Capital Region Police Office",
      "donations": 88,
      "seats": 1,
      "tableAssignment": "29",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 78,
      "agency": "Philippine National Railways",
      "donations": 31,
      "seats": 1,
      "tableAssignment": "29",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 79,
      "agency": "PHILUSA Corporation",
      "donations": 31,
      "seats": 1,
      "tableAssignment": "29",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 80,
      "agency": "Police Regional Office CALABARZON Camp BGen Vicentel Lim, Calamba City",
      "donations": 60,
      "seats": 1,
      "tableAssignment": "29",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 81,
      "agency": "Polytechnic University of the Philippines Tau Gamma Triskelion",
      "donations": 76,
      "seats": 1,
      "tableAssignment": "29",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 82,
      "agency": "Poveda Parent’s Association",
      "donations": 83,
      "seats": 1,
      "tableAssignment": "29",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 83,
      "agency": "Primer Resources Corp/Primer Group of Companies",
      "donations": 68,
      "seats": 1,
      "tableAssignment": "30",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 84,
      "agency": "Robinsons Retail Holdings Inc. ",
      "donations": 66,
      "seats": 1,
      "tableAssignment": "30",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 85,
      "agency": "RR Donnelley",
      "donations": 65,
      "seats": 2,
      "tableAssignment": "30",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 86,
      "agency": "Rustan Supercenters Inc.",
      "donations": 86,
      "seats": 2,
      "tableAssignment": "30",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 87,
      "agency": "San Beda College - Alabang",
      "donations": 52,
      "seats": 1,
      "tableAssignment": "30",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 88,
      "agency": "San Lazaro Hospital",
      "donations": 74,
      "seats": 1,
      "tableAssignment": "30",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 89,
      "agency": "San Miguel Corporation",
      "donations": 76,
      "seats": 1,
      "tableAssignment": "30",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 90,
      "agency": "San Miguel National High School",
      "donations": 50,
      "seats": 1,
      "tableAssignment": "30",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 91,
      "agency": "Shangri-La at The Fort, Manila",
      "donations": 99,
      "seats": 1,
      "tableAssignment": "30",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 92,
      "agency": "Soka Gakkai International of the Philippines",
      "donations": 98,
      "seats": 1,
      "tableAssignment": "31",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 93,
      "agency": "Solaire Resort and Casino",
      "donations": 77,
      "seats": 1,
      "tableAssignment": "31",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 94,
      "agency": "St. John Biocare and Dialysis Center",
      "donations": 40,
      "seats": 1,
      "tableAssignment": "31",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 95,
      "agency": "St. Jude College",
      "donations": 34,
      "seats": 1,
      "tableAssignment": "31",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 96,
      "agency": "St. Victoria Hospital",
      "donations": 34,
      "seats": 1,
      "tableAssignment": "31",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 97,
      "agency": "Stellar Philippines Inc.",
      "donations": 70,
      "seats": 1,
      "tableAssignment": "31",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 98,
      "agency": "Taihei Alltech Construction Philippines Inc.",
      "donations": 71,
      "seats": 2,
      "tableAssignment": "31",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 99,
      "agency": "Tau Gamma Phi - Kalumpang Community Chapter",
      "donations": 50,
      "seats": 1,
      "tableAssignment": "31",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 100,
      "agency": "TAU GAMMA PHI - Triskelion Marikina Council",
      "donations": 87,
      "seats": 1,
      "tableAssignment": "31",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 101,
      "agency": "Tau Gamma Phi / Sigma Triskelion Grand Fraternity / Sorority Montalban Municipal Council",
      "donations": 76,
      "seats": 1,
      "tableAssignment": "31",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 102,
      "agency": "Tauan Alumni Organization - TAU MU USA",
      "donations": 32,
      "seats": 1,
      "tableAssignment": "32",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 103,
      "agency": "The Purefoods Hormel Company, Inc.",
      "donations": 73,
      "seats": 1,
      "tableAssignment": "32",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 104,
      "agency": "The United Methodist Church",
      "donations": 32,
      "seats": 1,
      "tableAssignment": "32",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 105,
      "agency": "Tommie Creative Inc.",
      "donations": 41,
      "seats": 1,
      "tableAssignment": "32",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 106,
      "agency": "Toyota Manila Bay Corp.",
      "donations": 57,
      "seats": 2,
      "tableAssignment": "32",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 107,
      "agency": "Toyota New Vios Philippines",
      "donations": 62,
      "seats": 1,
      "tableAssignment": "32",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 108,
      "agency": "Universal Robina Corporation",
      "donations": 37,
      "seats": 2,
      "tableAssignment": "32",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 109,
      "agency": "University of Santo Tomas - Medicine Student Council",
      "donations": 60,
      "seats": 1,
      "tableAssignment": "32",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 110,
      "agency": "Valerie Products Manufacturing Inc.",
      "donations": 90,
      "seats": 1,
      "tableAssignment": "32",
      "award": "GABRIELA SILANG AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 111,
      "agency": "520th Air Base Wing, Philippine Air Force",
      "donations": 123,
      "seats": 2,
      "tableAssignment": "15",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 112,
      "agency": "Barangay 28, Zone 3 Caloocan City",
      "donations": 103,
      "seats": 2,
      "tableAssignment": "6",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 113,
      "agency": "Barangay Commonwealth",
      "donations": 142,
      "seats": 2,
      "tableAssignment": "8",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 114,
      "agency": "Cainta Life Savers, Inc.",
      "donations": 145,
      "seats": 2,
      "tableAssignment": "9",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 115,
      "agency": "Capitol Medical Center Colleges",
      "donations": 117,
      "seats": 2,
      "tableAssignment": "10",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 116,
      "agency": "City Government of Makati",
      "donations": 148,
      "seats": 2,
      "tableAssignment": "11",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 117,
      "agency": "Commonwealth Hospital and Medical Center",
      "donations": 145,
      "seats": 2,
      "tableAssignment": "16",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 118,
      "agency": "Department of Health",
      "donations": 147,
      "seats": 2,
      "tableAssignment": "16",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 119,
      "agency": "Don Bosco Technical Institute of Makati",
      "donations": 144,
      "seats": 2,
      "tableAssignment": "16",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 120,
      "agency": "EMD Technologies Philippines Inc.",
      "donations": 117,
      "seats": 2,
      "tableAssignment": "16",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 121,
      "agency": "Gat Andres Bonifacio Memorial Medical Center",
      "donations": 107,
      "seats": 2,
      "tableAssignment": "16",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 122,
      "agency": "Global Comfort Group Corporation",
      "donations": 181,
      "seats": 2,
      "tableAssignment": "17",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 123,
      "agency": "Helping Hands Club Inc., Brgy. Iba, Meycauayan City Bulacan",
      "donations": 118,
      "seats": 2,
      "tableAssignment": "17",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 124,
      "agency": "Intellicare/Asalus Corporation",
      "donations": 104,
      "seats": 2,
      "tableAssignment": "17",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 125,
      "agency": "Lina Group of Companies",
      "donations": 101,
      "seats": 2,
      "tableAssignment": "17",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 126,
      "agency": "Lyceum of the Philippines University – Cavite",
      "donations": 162,
      "seats": 2,
      "tableAssignment": "17",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 127,
      "agency": "Mary Johnston Hospital",
      "donations": 162,
      "seats": 2,
      "tableAssignment": "18",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 128,
      "agency": "Municipality of  San Mateo, Rizal",
      "donations": 156,
      "seats": 2,
      "tableAssignment": "18",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 129,
      "agency": "National Fire Training Institute",
      "donations": 152,
      "seats": 2,
      "tableAssignment": "18",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 130,
      "agency": "ON Semiconductor Philippines Incorporated",
      "donations": 160,
      "seats": 0,
      "tableAssignment": "",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 131,
      "agency": "One Food Group Management Services, Inc.",
      "donations": 176,
      "seats": 2,
      "tableAssignment": "18",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 132,
      "agency": "Order of the Triskelion, Quezon City Hall",
      "donations": 127,
      "seats": 2,
      "tableAssignment": "18",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 133,
      "agency": "Our Lady of Mercy Parish Church",
      "donations": 111,
      "seats": 2,
      "tableAssignment": "19",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 134,
      "agency": "PARDSS Foundation International",
      "donations": 119,
      "seats": 2,
      "tableAssignment": "19",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 135,
      "agency": "Philippine Coast Guard",
      "donations": 121,
      "seats": 2,
      "tableAssignment": "19",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 136,
      "agency": "Philippine Dental Association",
      "donations": 123,
      "seats": 2,
      "tableAssignment": "19",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 137,
      "agency": "Quezon City Health Department",
      "donations": 168,
      "seats": 2,
      "tableAssignment": "19",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 138,
      "agency": "Quezon City Police District",
      "donations": 166,
      "seats": 2,
      "tableAssignment": "20",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 139,
      "agency": "Roosevelt College Rodriguez Batch 88 - Montalban Rizal",
      "donations": 114,
      "seats": 2,
      "tableAssignment": "20",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 140,
      "agency": "Rotary Club Makati Magilas",
      "donations": 107,
      "seats": 2,
      "tableAssignment": "20",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 141,
      "agency": "San Beda University - Rizal",
      "donations": 109,
      "seats": 1,
      "tableAssignment": "20",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 142,
      "agency": "San Beda University Manila",
      "donations": 170,
      "seats": 2,
      "tableAssignment": "20",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 143,
      "agency": "Sitel Group",
      "donations": 171,
      "seats": 2,
      "tableAssignment": "20",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 144,
      "agency": "Sky Cable",
      "donations": 141,
      "seats": 2,
      "tableAssignment": "21",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 145,
      "agency": "St. Mary Academy of Sto. Niño, Meycauayan City, Bulacan",
      "donations": 127,
      "seats": 2,
      "tableAssignment": "21",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 146,
      "agency": "Technological University of the Philippines ",
      "donations": 135,
      "seats": 3,
      "tableAssignment": "21",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 147,
      "agency": "Unbound Manila Project",
      "donations": 175,
      "seats": 2,
      "tableAssignment": "21",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 148,
      "agency": "United Coconut Planters Life Assurance Corporation",
      "donations": 123,
      "seats": 2,
      "tableAssignment": "21",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 149,
      "agency": "Word of Hope Christian Family Church",
      "donations": 198,
      "seats": 2,
      "tableAssignment": "22",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 150,
      "agency": "World Health Organization Western Pacific Regional Office",
      "donations": 174,
      "seats": 2,
      "tableAssignment": "22",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 151,
      "agency": "World Mission Society Church of God",
      "donations": 119,
      "seats": 2,
      "tableAssignment": "22",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 152,
      "agency": "Wyeth Philippines, Inc.",
      "donations": 114,
      "seats": 2,
      "tableAssignment": "22",
      "award": "APOLINARIO MABINI AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 153,
      "agency": "Adventist University of the Philippines ",
      "donations": 227,
      "seats": 3,
      "tableAssignment": "11",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 154,
      "agency": "Bernardino General Hospital 1",
      "donations": 268,
      "seats": 3,
      "tableAssignment": "11",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 155,
      "agency": "Bernardino General Hospital 2",
      "donations": 239,
      "seats": 3,
      "tableAssignment": "12",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 156,
      "agency": "DOH Center for Health Development Mimaropa",
      "donations": 209,
      "seats": 2,
      "tableAssignment": "12",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 157,
      "agency": "Fatima University Medical Center",
      "donations": 206,
      "seats": 3,
      "tableAssignment": "12",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 158,
      "agency": "I LOVE STA. ROSA Foundation",
      "donations": 270,
      "seats": 3,
      "tableAssignment": "12",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 159,
      "agency": "ICCT Colleges Foundation Inc.",
      "donations": 279,
      "seats": 1,
      "tableAssignment": "13",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 160,
      "agency": "Lyceum of the Philippines University – Manila",
      "donations": 292,
      "seats": 3,
      "tableAssignment": "13",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 161,
      "agency": "Most Holy Church of God in Christ Jesus",
      "donations": 251,
      "seats": 3,
      "tableAssignment": "13",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 162,
      "agency": "National Jail Management and Penology Training Institute",
      "donations": 235,
      "seats": 0,
      "tableAssignment": "",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 163,
      "agency": "NPC Ladies Foundation Inc.",
      "donations": 239,
      "seats": 3,
      "tableAssignment": "13",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 164,
      "agency": "Ospital ng Maynila Medical Center",
      "donations": 270,
      "seats": 4,
      "tableAssignment": "14",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 165,
      "agency": "Ospital ng Sampaloc",
      "donations": 291,
      "seats": 3,
      "tableAssignment": "14",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 166,
      "agency": "PAGCOR ",
      "donations": 297,
      "seats": 3,
      "tableAssignment": "14",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 167,
      "agency": "Pamahalaang Barangay Dolores, Taytay Rizal",
      "donations": 266,
      "seats": 3,
      "tableAssignment": "15",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 168,
      "agency": "Teletech",
      "donations": 291,
      "seats": 3,
      "tableAssignment": "15",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 169,
      "agency": "Unbound Antipolo Project",
      "donations": 229,
      "seats": 3,
      "tableAssignment": "15",
      "award": "ANTONIO LUNA AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 170,
      "agency": "Angono Life Savers(ALSI), Inc.",
      "donations": 317,
      "seats": 3,
      "tableAssignment": "8",
      "award": "MELCHORA AQUINO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 171,
      "agency": "APC by Schneider Electric",
      "donations": 386,
      "seats": 3,
      "tableAssignment": "9",
      "award": "MELCHORA AQUINO AWARD",
      "extraAward": "LAPU-LAPU AWARD",
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 172,
      "agency": "Emilio Aguinaldo College Medical Center",
      "donations": 359,
      "seats": 3,
      "tableAssignment": "9",
      "award": "MELCHORA AQUINO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 173,
      "agency": "Los Baños Municipal Health Office",
      "donations": 314,
      "seats": 0,
      "tableAssignment": "",
      "award": "MELCHORA AQUINO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 174,
      "agency": "Marikina City Health Office",
      "donations": 393,
      "seats": 3,
      "tableAssignment": "9",
      "award": "MELCHORA AQUINO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 175,
      "agency": "Philippine National Police - Special Action Force",
      "donations": 321,
      "seats": 3,
      "tableAssignment": "10",
      "award": "MELCHORA AQUINO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 176,
      "agency": "Philippine National Police Academy",
      "donations": 365,
      "seats": 3,
      "tableAssignment": "10",
      "award": "MELCHORA AQUINO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 177,
      "agency": "Police Community Relations Group - Philippine National Police",
      "donations": 307,
      "seats": 3,
      "tableAssignment": "10",
      "award": "MELCHORA AQUINO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 178,
      "agency": "Teleperformance - COTW ",
      "donations": 371,
      "seats": 0,
      "tableAssignment": "",
      "award": "MELCHORA AQUINO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 179,
      "agency": "The Feast Bay Area",
      "donations": 366,
      "seats": 3,
      "tableAssignment": "11",
      "award": "MELCHORA AQUINO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 180,
      "agency": "Alagang Kapatid Foundation Inc.",
      "donations": 529,
      "seats": 3,
      "tableAssignment": "6",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 181,
      "agency": "Army Station Hospital - 2nd Infantry (Jungle Fighter) Division Philippine Army",
      "donations": 567,
      "seats": 3,
      "tableAssignment": "4",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 182,
      "agency": "D.M. Consunji, Inc.",
      "donations": 569,
      "seats": 3,
      "tableAssignment": "6",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 183,
      "agency": "Donate Philippines Inc.",
      "donations": 738,
      "seats": 3,
      "tableAssignment": "1 presidential    2 - Table 5",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 184,
      "agency": "DZMM ",
      "donations": 717,
      "seats": 4,
      "tableAssignment": "1",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 185,
      "agency": "Go Forward Biñan Foundation, Inc.",
      "donations": 721,
      "seats": 3,
      "tableAssignment": "6",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 186,
      "agency": "Las Piñas City Health Office",
      "donations": 653,
      "seats": 5,
      "tableAssignment": "7",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 187,
      "agency": "Municipality of Angono",
      "donations": 579,
      "seats": 3,
      "tableAssignment": "7",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 188,
      "agency": "Quezon City General Hospital",
      "donations": 630,
      "seats": 3,
      "tableAssignment": "7",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 189,
      "agency": "Sta. Ana Hospital",
      "donations": 931,
      "seats": 3,
      "tableAssignment": "8",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 190,
      "agency": "Txtfire Philippines Foundation Inc.",
      "donations": 503,
      "seats": 3,
      "tableAssignment": "8",
      "award": "GREGORIO DEL PILAR AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 191,
      "agency": "Justice Jose Abad Santos General Hospital",
      "donations": 1264,
      "seats": 5,
      "tableAssignment": "3",
      "award": "ANDRES BONIFACIO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 192,
      "agency": "Manila Health Department",
      "donations": 1007,
      "seats": 5,
      "tableAssignment": "5",
      "award": "ANDRES BONIFACIO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 193,
      "agency": "Office of the Vice Mayor Quezon City",
      "donations": 1074,
      "seats": 5,
      "tableAssignment": "1 presidential    4 - table 5",
      "award": "ANDRES BONIFACIO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 194,
      "agency": "SM Foundation, Inc.",
      "donations": 1184,
      "seats": 1,
      "tableAssignment": "2",
      "award": "ANDRES BONIFACIO AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 195,
      "agency": "Iglesia ni Cristo",
      "donations": 2010,
      "seats": 2,
      "tableAssignment": "2",
      "award": "JOSE RIZAL AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 196,
      "agency": "City Government of Taguig",
      "donations": 2086,
      "seats": 5,
      "tableAssignment": "2",
      "award": "JOSE RIZAL AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 197,
      "agency": "City Government of Muntinlupa ",
      "donations": 3236,
      "seats": 7,
      "tableAssignment": "1 presidential    6 - table 3",
      "award": "JOSE RIZAL AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    },
    {
      "id": 198,
      "agency": "Members, Church of God International",
      "donations": 6710,
      "seats": 8,
      "tableAssignment": "4",
      "award": "JOSE RIZAL AWARD",
      "extraAward": null,
      "recipients": null,
      "photo": null,
      "completed": false
    }
   ];

module.exports = function(){
    return DataSource;
}