package doh.nvbsp.imu.dugongbayani.lib.datasource;

import java.util.ArrayList;

import doh.nvbsp.imu.dugongbayani.lib.models.Agency;

public class Agencies {

    public static ArrayList<Agency> all(){
        ArrayList<Agency> data = new ArrayList<>();
        data.add(new Agency("1","Members, Church of God International","5","2"));
        data.add(new Agency("2","City Government of Muntinlupa","10","5"));
        data.add(new Agency("3","City Government of Taguig","7","6"));
        data.add(new Agency("4","Iglesia ni Cristo","5","7"));
        data.add(new Agency("5","Justice Jose Abad Santos General Hospital","5","1"));
        data.add(new Agency("6","SM Foundation, Inc.","5","1"));
        data.add(new Agency("7","Office of the Vice Mayor Quezon City","5","2"));
        data.add(new Agency("8","Manila Health Department","5","7"));
        data.add(new Agency("9","Sta. Ana Hospital","3","6"));
        data.add(new Agency("10","Donate Philippines Inc.","3","8"));
        data.add(new Agency("11","GO FORWARD Biñan Foundation, Inc.","3","8"));
        data.add(new Agency("12","DZMM","5","9"));
        data.add(new Agency("13","Las Piñas City Health Office","5","9"));
        data.add(new Agency("14","Quezon City General Hospital","3","8"));
        data.add(new Agency("15","Municipality of Angono","3","10"));
        data.add(new Agency("16","D.M. Consunji, Inc.","3","10"));
        data.add(new Agency("17","Army Station Hospital - 2nd Infantry (Jungle Fighter) Division Philippine Army","3","10"));
        data.add(new Agency("18","Alagang Kapatid Foundation Inc.","3","11"));
        data.add(new Agency("19","Txtfire Philippines Foundation Inc.","3","11"));
        data.add(new Agency("20","Marikina City Health Office","3","11"));
        data.add(new Agency("21","APC by Schneider Electric","3","12"));
        data.add(new Agency("22","Teleperformance - COTW","3","12"));
        data.add(new Agency("23","The Feast Bay Area","3","12"));
        data.add(new Agency("24","Philippine National Police Academy","3","13"));
        data.add(new Agency("25","Emilio Aguinaldo College Medical Center","3","13"));
        data.add(new Agency("26","Philippine National Police - Special Action Force","3","13"));
        data.add(new Agency("27","Angono Life Savers(ALSI)); Inc.","3","14"));
        data.add(new Agency("28","Los Baños Municipal Health Office","3","14"));
        data.add(new Agency("29","Police Community Relations Group - Philippine National Police","3","14"));
        data.add(new Agency("30","PAGCOR","3","15"));
        data.add(new Agency("31","Lyceum of the Philippines University – Manila","3","15"));
        data.add(new Agency("32","Ospital ng Sampaloc","3","15"));
        data.add(new Agency("33","Teletech","3","16"));
        data.add(new Agency("34","ICCT Colleges Foundation Inc.","3","16"));
        data.add(new Agency("35","I LOVE STA. ROSA Foundation","3","16"));
        data.add(new Agency("36","Ospital ng Maynila Medical Center","3","17"));
        data.add(new Agency("37","Bernardino General Hospital 1","3","17"));
        data.add(new Agency("38","Pamahalaang Barangay Dolores, Taytay Rizal","3","17"));
        data.add(new Agency("39","Most Holy Church of God in Christ Jesus","3","18"));
        data.add(new Agency("40","Bernardino General Hospital 2","3","18"));
        data.add(new Agency("41","NPC Ladies Foundation Inc.","3","18"));
        data.add(new Agency("42","National Jail Management and Penology Training Institute","3","19"));
        data.add(new Agency("43","Unbound Antipolo Project","3","19"));
        data.add(new Agency("44","Adventist University of the Philippines","3","19"));
        data.add(new Agency("45","Fatima University Medical Center","3","20"));
        data.add(new Agency("46","520th Air Base Wing, Philippine Air Force","2","28"));
        data.add(new Agency("47","Barangay 28, Zone 3 Caloocan City","2","28"));
        data.add(new Agency("48","Barangay Commonwealth","2","28"));
        data.add(new Agency("49","Cainta Life Savers, Inc.","2","28"));
        data.add(new Agency("50","Capitol Medical Center Colleges","2","28"));
        data.add(new Agency("51","City Government of Makati","2","27"));
        data.add(new Agency("52","Commonwealth Hospital and Medical Center","2","27"));
        data.add(new Agency("53","Department of Health","2","27"));
        data.add(new Agency("54","DOH Center for Health Development Mimaropa","2","27"));
        data.add(new Agency("55","Don Bosco Technical Institute of Makati","2","27"));
        data.add(new Agency("56","EMD Technologies Philippines Inc.","2","26"));
        data.add(new Agency("57","Gat Andres Bonifacio Memorial Medical Center","2","26"));
        data.add(new Agency("58","Global Comfort Group Corporation (Hotel Sogo)","2","26"));
        data.add(new Agency("59","Helping Hands Club Inc., Brgy. Iba, Meycauayan City Bulacan","2","26"));
        data.add(new Agency("60","Intellicare/Asalus Corporation","2","26"));
        data.add(new Agency("61","Lina Group of Companies","2","25"));
        data.add(new Agency("62","Lyceum of the Philippines University – Cavite","2","25"));
        data.add(new Agency("63","Mary Johnston Hospital","2","25"));
        data.add(new Agency("64","Municipality of  San Mateo, Rizal","2","25"));
        data.add(new Agency("65","National Fire Training Institute","2","25"));
        data.add(new Agency("66","ON Semiconductor Philippines Incorporated","2","24"));
        data.add(new Agency("67","One Food Group Management Services, Inc.","2","24"));
        data.add(new Agency("68","Order of the Triskelion, Quezon City Hall","2","24"));
        data.add(new Agency("69","Our Lady of Mercy Parish Church","2","24"));
        data.add(new Agency("70","PARDSS Foundation International","2","24"));
        data.add(new Agency("71","Philippine Coast Guard","2","23"));
        data.add(new Agency("72","Philippine Dental Association","2","23"));
        data.add(new Agency("73","Quezon City Health Department","2","23"));
        data.add(new Agency("74","Quezon City Police District","2","23"));
        data.add(new Agency("75","Roosevelt College Rodriguez Batch 88 - Montalban Rizal","2","23"));
        data.add(new Agency("76","Rotary Club - Makati","2","22"));
        data.add(new Agency("77","San Beda College Rizal","2","22"));
        data.add(new Agency("78","San Beda University Manila","2","22"));
        data.add(new Agency("79","Sitel Group","2","22"));
        data.add(new Agency("80","Sky Cable","2","22"));
        data.add(new Agency("81","St. Mary Academy of Sto. Niño, Meycauayan City, Bulacan","2","21"));
        data.add(new Agency("82","Technological University of the Philippines","2","21"));
        data.add(new Agency("83","Unbound Manila Project","2","21"));
        data.add(new Agency("84","United Coconut Planters Life Assurance Corporation","2","21"));
        data.add(new Agency("85","Word of Hope Christian Family Church","2","21"));
        data.add(new Agency("86","World Health Organization Western Pacific Regional Office","2","20"));
        data.add(new Agency("87","World Mission Society Church of God","2","20"));
        data.add(new Agency("88","Wyeth Philippines, Inc.","2","20"));
        data.add(new Agency("89","51st Engineer Brigade, Philippine Army","1","39"));
        data.add(new Agency("90","Abenson Group of Companies","1","39"));
        data.add(new Agency("91","Alaska Milk Corporation, San Pedro Laguna","1","39"));
        data.add(new Agency("92","ASA Philippines Foundation Inc.","1","39"));
        data.add(new Agency("93","Asia Pacific College","1","39"));
        data.add(new Agency("94","Barangay Balibago","1","39"));
        data.add(new Agency("95","Berjaya Philippines","1","39"));
        data.add(new Agency("96","Binangonan Life Savers, Inc.","1","39"));
        data.add(new Agency("97","Bureau of Customs","1","39"));
        data.add(new Agency("98","Bureau of Fire Protection, National Capital Region","1","39"));
        data.add(new Agency("99","Burlington","1","38"));
        data.add(new Agency("100","California Clothings Inc.","1","38"));
        data.add(new Agency("101","Cathedral of Praise","1","38"));
        data.add(new Agency("102","Cavite Naval Hospital","1","38"));
        data.add(new Agency("103","Centro Manufacturing Corporation","1","38"));
        data.add(new Agency("104","Christine Village Homeowners Association Inc.","1","38"));
        data.add(new Agency("105","Christ\"s Commission Fellowship - Baliuag, Bulacan","1","38"));
        data.add(new Agency("106","City of Biñan Triskelion Executive Council","1","38"));
        data.add(new Agency("107","Civic Merchandising Inc","1","38"));
        data.add(new Agency("108","Civil Aviation Authority of the Philippines","1","38"));
        data.add(new Agency("109","Civil Service Commission","1","37"));
        data.add(new Agency("110","Coca-Cola Beverages Philippines, Inc.","1","37"));
        data.add(new Agency("111","De La Salle Araneta University","1","37"));
        data.add(new Agency("112","De La Salle University – COSCA LOVE","1","37"));
        data.add(new Agency("113","Department Of Health Center for Health Development - CaLaBaRZon","1","37"));
        data.add(new Agency("114","Department of Health Metro Manila - Center for Health Development","1","37"));
        data.add(new Agency("115","Don Bosco School (Salesian Sisters) Inc.","1","37"));
        data.add(new Agency("116","Emperador Distillers Inc.","1","37"));
        data.add(new Agency("117","Eulogio \"Amang\" Rodriguez Institute of Science and Technology","1","37"));
        data.add(new Agency("118","Far Eastern University - Junior Student Medical Society","1","37"));
        data.add(new Agency("119","Fatima Church San Pedro","1","36"));
        data.add(new Agency("120","Firefly Electric Lighting Corporation","1","36"));
        data.add(new Agency("121","Five9 Philippines, Inc.","1","36"));
        data.add(new Agency("122","Gemphil Technologies Inc.","1","36"));
        data.add(new Agency("123","GK Towerville - Bulacan","1","36"));
        data.add(new Agency("124","Glades International Corporation","1","36"));
        data.add(new Agency("125","Grace General Hospital, Inc.","1","36"));
        data.add(new Agency("126","Higher Rock Christian Church","1","36"));
        data.add(new Agency("127","Hizon Laboratories, Incorporated","1","36"));
        data.add(new Agency("128","Honda Cars Philippines Inc.","1","36"));
        data.add(new Agency("129","Iglesia ng Dios Kay Cristo Jesus Haligi at Suhay ng Katotohanan","1","35"));
        data.add(new Agency("130","Infosys BPM Limited - Philippine Branch","1","35"));
        data.add(new Agency("131","Jollibee Region IV-A","1","35"));
        data.add(new Agency("132","Josefina Manufacturing Inc.","1","35"));
        data.add(new Agency("133","Kaertech Electronics Philippines","1","35"));
        data.add(new Agency("134","Kawit Rural Health Unit","1","35"));
        data.add(new Agency("135","Kilusan sa Jollibee","1","35"));
        data.add(new Agency("136","Kythe A","1","35"));
        data.add(new Agency("137","La Consolacion College, Deparo Novaliches","1","35"));
        data.add(new Agency("138","La Filipina Uy Gongco","1","35"));
        data.add(new Agency("139","La Salle Greenhills","1","34"));
        data.add(new Agency("140","Lafarge Holcim Aggrerates Inc.","1","34"));
        data.add(new Agency("141","Lyceum of the Philippines University – Laguna","1","34"));
        data.add(new Agency("142","Magic-5 PUP","1","34"));
        data.add(new Agency("143","Magnolia Corporation","1","34"));
        data.add(new Agency("144","Makati Shangri-La Hotel","1","34"));
        data.add(new Agency("145","Mallers Management Corporation","1","34"));
        data.add(new Agency("146","Manila Ocean Park and Hotel H2O","1","34"));
        data.add(new Agency("147","Manuel L. Quezon University","1","34"));
        data.add(new Agency("148","Marikina Valley Medical Center","1","34"));
        data.add(new Agency("149","Metropolitan Manila Development Authority","1","33"));
        data.add(new Agency("150","Meycauayan Doctors Hospital and Medical Center, Meycauayan City, Bulacan","1","33"));
        data.add(new Agency("151","MN Electro Industrial Supply","1","33"));
        data.add(new Agency("152","Multigeneration of Active Apostolic Guardians Association of the Philippines (MAAGAP) Inc.","1","33"));
        data.add(new Agency("153","Municipal Government of Tanay, Rizal","1","33"));
        data.add(new Agency("154","National Bureau of Investigation","1","33"));
        data.add(new Agency("155","National Police Commission","1","33"));
        data.add(new Agency("156","National University","1","33"));
        data.add(new Agency("157","Naval Installation Command, Philippine Navy","1","33"));
        data.add(new Agency("158","Nokia Technology Center Philippines, Inc.","1","33"));
        data.add(new Agency("159","Novotel, Manila","1","32"));
        data.add(new Agency("160","Office of Congressman Yul Servo","1","32"));
        data.add(new Agency("161","Order of the Triskelion, Bulacan Chapter","1","32"));
        data.add(new Agency("162","P. Imes Corp.","1","32"));
        data.add(new Agency("163","Pfizer Philippines Foundation","1","32"));
        data.add(new Agency("164","PHAPCares Foundation, Inc.","1","32"));
        data.add(new Agency("165","Philippine National Police - National Capital Region Police Office","1","32"));
        data.add(new Agency("166","Philippine National Railways","1","32"));
        data.add(new Agency("167","PHILUSA Corporation","1","32"));
        data.add(new Agency("168","Police Regional Office CALABARZON Camp BGen Vicentel Lim, Calamba City","1","32"));
        data.add(new Agency("169","Polytechnic University of the Philippines Tau Gamma Triskelion","1","31"));
        data.add(new Agency("170","Poveda Parent’s Association","1","31"));
        data.add(new Agency("171","Primer Resources Corp/Primer Group of Companies","1","31"));
        data.add(new Agency("172","Robinsons Retail Holdings Inc.","1","31"));
        data.add(new Agency("173","RR Donnelley","1","31"));
        data.add(new Agency("174","Rustan Supercenters Inc.","1","31"));
        data.add(new Agency("175","San Beda College - Alabang","1","31"));
        data.add(new Agency("176","San Lazaro Hospital","1","31"));
        data.add(new Agency("177","San Miguel Corporation","1","31"));
        data.add(new Agency("178","San Miguel National High School","1","31"));
        data.add(new Agency("179","Shangri-La at The Fort, Manila","1","30"));
        data.add(new Agency("180","Soka Gakkai International of the Philippines","1","30"));
        data.add(new Agency("181","Solaire Resort and Casino","1","30"));
        data.add(new Agency("182","St. John Biocare and Dialysis Center","1","30"));
        data.add(new Agency("183","St. Jude College","1","30"));
        data.add(new Agency("184","St. Victoria Hospital","1","30"));
        data.add(new Agency("185","Stellar Philippines Inc.","1","30"));
        data.add(new Agency("186","Taihei Alltech Construction (Phil)); Inc.","1","30"));
        data.add(new Agency("187","Tau Gamma Phi - Kalumpang Community Chapter","1","30"));
        data.add(new Agency("188","TAU GAMMA PHI - Triskelion Marikina Council","1","30"));
        data.add(new Agency("189","Tau Gamma Phi / Sigma Triskelion Grand Fraternity / Sorority Montalban Municipal Council","1","29"));
        data.add(new Agency("190","The Purefoods Hormel Company, Inc.","1","29"));
        data.add(new Agency("191","Tommie Creative Inc.","1","29"));
        data.add(new Agency("192","Toyota Manila Bay Corp.","1","29"));
        data.add(new Agency("193","Toyota New Vios Philippines","1","29"));
        data.add(new Agency("194","United Methodist Church","1","29"));
        data.add(new Agency("195","Universal Robina Corporation","1","29"));
        data.add(new Agency("196","University of Santo Tomas - Student Medical Society","1","29"));
        data.add(new Agency("197","Valerie Products Manufacturing Inc.","1","29"));
        data.add(new Agency("198","Tauan Alumini Organization - TAU MU USA","1","29"));

        return data;
    }
}
